database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  db: on-air
redis:
  host: localhost
  port: 6379
  password: redis
  db: 1
  ttl: "10m"
server:
  port: 2000
auth:
  secret-key: mysecretkey
  lifetime: 60 m
services:
  flights: 
    url: "http://example.com"
    timeout: "60s"
