database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  db: on-air
redis:
  host: localhost
  port: 6379
  password: redis
  db: 1
server:
  port: 2000
auth:
  secret-key: mysecretkey
  lifetime: 60 m
gatepay:
  merchant_code: 788
  terminal_id: 134754358
  redirect_url: 
  cert_file:
