database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  db: on-air
redis:
  host: localhost
  port: 6379
  password: redis
  db: 1
  ttl: "10m"
server:
  port: 2000
auth:
  secret-key: mysecretkey
  expires_in: 60 m
gatepay:
  merchant_code: 788
  terminal_id: 134754358
  redirect_url: "http://example.com/payment/callBack"
  cert_file: "server/services/pasargad/certFile.xml"
  worker:
    enabled: true
    interval: 10000000
    iteration: 3
    concurency: 2
    limit: 3
services:
  flights: 
    url: "http://example.com"
    timeout: "60s"