DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS ticket_passengers;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS users;

